### ISSUE TITLE
English to Korean translation problem

### ISSUE THREAD

**Issue by Sallos725** [mololab/json-translator#9]
Hi. I was trying to translate a certain json file from English to Korean but I have faced into a problem and it seems to it cannot translate in some sentence or a word. I have tried all three translators possible, and the problem was: 

undefined:63
        "quest.crystals.description":"This planet has a unique ecosystem with biomes comprised of hot temperatures permeated from large lava lakes at its core, to cooler

 in JSON at position 10080ken
    at JSON.parse (<anonymous>)
    at _callee2$ (C:\Users\user\AppData\Roaming\npm\node_modules\@parvineyvazov\json-translator\dist\json-translator.cjs.development.js:1412:26)
    at tryCatch (C:\Users\user\AppData\Roaming\npm\node_modules\@parvineyvazov\json-translator\dist\json-translator.cjs.development.js:116:40)
    at Generator.invoke [as _invoke] (C:\Users\user\AppData\Roaming\npm\node_modules\@parvineyvazov\json-translator\dist\json-translator.cjs.development.js:347:22)
    at Generator.next (C:\Users\user\AppData\Roaming\npm\node_modules\@parvineyvazov\json-translator\dist\json-translator.cjs.development.js:172:21)
    at asyncGeneratorStep (C:\Users\user\AppData\Roaming\npm\node_modules\@parvineyvazov\json-translator\dist\json-translator.cjs.development.js:16:24)
    at _next (C:\Users\user\AppData\Roaming\npm\node_modules\@parvineyvazov\json-translator\dist\json-translator.cjs.development.js:38:9)

is there anything I can do? Thank you.

Sorry this is my very first time to using github and issuing so if you need more infomation, just let me know.

**Comment by Sallos725** [comment]
also found that if the json file is over 4000 lines, it seems to give up to translate. From line 3000 the lesser it becomes to translate, and when it reaches over 4000th line, it is not translated at all. Even though I saw some logs but I ignored because it was due to the large file.

**Comment by ParvinEyvazov** [comment]
@Sallos725 can you please try other translation services such as Bing Microsoft Translate, Libre Translate, Argos Translate

[v1.8.0](https://mololab.org/jsontt/npm)
